---
title: "R Notebook"
output: html_notebook
---
```{r}
df=read.csv('./original_gsedata.csv',header = TRUE)
head(df)
```



```{r}
scale_df=data.frame(scale(data[1:5724]))
scale_df.pca=prcomp(scaled_df[1:5724])
```


```{r}
y1 = df$class
df1_pca = data.frame(scale_df.pca$x)[1:24]
df1_pca$class = y1




```

```{r}
library('caret')
in_train = createDataPartition(y1 = df_pca$class, p= 0.8, list = FALSE)
train = df_pca[in_train,]
test = df_pca[-in_train,]

train %>% group_by(class) %>% summarise(B = length(class))


rows_to_delete_from_train = which(train$class=='Ta')[1:6]
train = train[-c(rows_to_delete_from_train),]
rows_to_add = train[c(rows_to_delete_from_train),]
test = rbind(test,rows_to_add)
train %>% group_by(class) %>% summarise(B = length(class))
test %>% group_by(class) %>% summarise(B = length(class))


```
```{r}
require(e1071)
m1 <- gknn(train,train$class, k= 10)
predict = gknn(train = train, test = test, k = 10)
table(m1,test$class)
```
```{r}
require(e1071)
library(class)

cancer_train <- df[1:30,]
cancer_test <- df[31:40,]

cancer_train_labels <- df[1:30,5725]
cancer_test_labels <- df[31:40,5725]
target <- factor(df$class)
df$class = target 
cancer_train_labels <- as.data.frame(cancer_train_labels)
cancer_test_labels <- as.data.frame(cancer_test_labels)

prc_test_pred <- knn(train = cancer_train, test = cancer_test,cl = cancer_train_labels, k=5)


```


