---
title: "Bladder Cancer - SVM Model Building"
output: html_notebook
---
```{r}
#Read the dataset
data=read.csv('./original_gsedata.csv',header = TRUE)
head(data)
```

```{r}
dim(data)
require(dplyr)
data %>% group_by(class) %>% summarise(B = length(class))
```

```{r}

```


```{r}
scaled_df=data.frame(scale(data[1:5724]))
scaled_df.pca=prcomp(scaled_df[1:5724])
screeplot(scaled_df.pca, type="lines")
```

```{r}
summary(scaled_df.pca)
```

```{r}
y=data$class
df_pca = data.frame(scaled_df.pca$x)[1:24]
df_pca$class = y
head(df_pca)
```

```{r}
#install.packages('caret') 
library('caret')
intrain = createDataPartition(y = df_pca$class, p= 0.7, list = FALSE)
training = df_pca[intrain,]
testing = df_pca[-intrain,]
```

```{r}
training %>% group_by(class) %>% summarise(B = length(class))
```

```{r}
require('dplyr')
rows_to_delete_from_train = which(training$class=='Ta')[1:6]
training = training[-c(rows_to_delete_from_train),]
rows_to_add = training[c(rows_to_delete_from_train),]
testing = rbind(testing,rows_to_add)
training %>% group_by(class) %>% summarise(B = length(class))
testing %>% group_by(class) %>% summarise(B = length(class))
```

```{r}
summary(df_pca)
```

```{r}
library(e1071)
training$class=as.factor(training$class)
svmfit = svm(class ~ ., data = training, kernel = "radial", cost = 10, scale = TRUE)
print(svmfit)
```

```{r}
plot(svmfit, training,PC1~PC2)
```


```{r}
test_pred <- predict(svmfit, newdata = testing)
test_pred
```


```{r}
caret::confusionMatrix(test_pred, as.factor(testing$class))
```

```{r}
require("MLmetrics")
F1_Score(as.factor(testing$class),test_pred, positive = NULL)
```




















